package render

const nftablesTemplate = `#!/usr/sbin/nft -f

# Generated by cnftctl. Manual edits may be overwritten.
# Docker-compatible cleanup: only delete and recreate inet hostfw.
table inet hostfw {}
delete table inet hostfw

include "` + WhitelistPath + `"

define WAN_IF = "{{ .WANInterface }}"
{{- if .TrustedEnabled }}
define TRUSTED_IFS = {{ quoteSet .TrustedInterfaces }}
{{- end }}
{{- if .DockerEnabled }}
define DOCKER_IFS = {{ quoteSet .DockerInterfaces }}
{{- end }}

table inet hostfw {
    {{- if .DDNSEnabled }}
    set ddns_whitelist_v4 { type ipv4_addr; flags timeout; timeout {{ .DDNSTTL }}; }
    set ddns_whitelist_v6 { type ipv6_addr; flags interval, timeout; timeout {{ .DDNSTTL }}; }

    {{- end }}
    include "` + OpenPortsPath + `"

    chain input {
        type filter hook input priority filter; policy drop;

        # ICMP must run before invalid drops for diagnostics, IPv6 NDP, and PMTUD.
        ip protocol icmp accept
        meta l4proto icmpv6 accept

        {{- if .TrustedEnabled }}
        iifname $TRUSTED_IFS accept

        {{- end }}
        ct state established,related accept
        meta l4proto tcp ct state invalid drop
        iifname "lo" accept
        {{- if .DockerEnabled }}
        iifname $DOCKER_IFS accept
        {{- end }}

        iifname $WAN_IF meta nfproto ipv4 fib saddr . iif oif missing drop
        iifname $WAN_IF ip6 saddr != fe80::/10 fib saddr oif missing drop

        tcp flags syn limit rate over 200/second burst 50 packets drop

        {{- if eq .SSHMode "open" }}
        iifname $WAN_IF tcp dport 22 accept
        {{- else if eq .SSHMode "whitelist-rate-limit" }}
        ip saddr $whitelist_v4 tcp dport 22 limit rate {{ .SSHRateLimit }} accept
        ip6 saddr $whitelist_v6 tcp dport 22 limit rate {{ .SSHRateLimit }} accept
        {{- if .DDNSEnabled }}
        ip saddr @ddns_whitelist_v4 tcp dport 22 limit rate {{ .SSHRateLimit }} accept
        ip6 saddr @ddns_whitelist_v6 tcp dport 22 limit rate {{ .SSHRateLimit }} accept
        {{- end }}
        {{- else }}
        ip saddr $whitelist_v4 tcp dport 22 accept
        ip6 saddr $whitelist_v6 tcp dport 22 accept
        {{- if .DDNSEnabled }}
        ip saddr @ddns_whitelist_v4 tcp dport 22 accept
        ip6 saddr @ddns_whitelist_v6 tcp dport 22 accept
        {{- end }}
        {{- end }}

        iifname $WAN_IF meta l4proto . th dport @open_ports accept
    }
{{- if .DockerEnabled }}

    chain forward_wan_gate {
        type filter hook forward priority filter - 1; policy accept;

        ip protocol icmp accept
        meta l4proto icmpv6 accept
        {{- if .TrustForwarding }}
        iifname $TRUSTED_IFS accept
        oifname $TRUSTED_IFS accept
        {{- end }}

        ct state established,related accept
        meta l4proto tcp ct state invalid drop

        meta nfproto ipv4 iifname $WAN_IF oifname $DOCKER_IFS ct status dnat jump docker_wan_allow
        meta nfproto ipv6 iifname $WAN_IF oifname $DOCKER_IFS jump docker_wan_allow_ipv6
    }

    chain docker_wan_allow {
        meta l4proto . ct original proto-dst @open_ports accept
        drop
    }

    chain docker_wan_allow_ipv6 {
        ct status dnat meta l4proto . ct original proto-dst @open_ports accept
        meta l4proto . th dport @open_ports accept
        drop
    }
{{- end }}

    chain output {
        type filter hook output priority filter; policy accept;
    }
}
`

const openPortsTemplate = `# Generated by cnftctl. Manual edits may be overwritten.
# Every port listed here is public from WAN for host services and Docker-published
# services when Docker WAN gating is enabled.

set open_ports {
    typeof meta l4proto . th dport
    flags interval
    elements = {
{{- if .OpenPorts }}
{{- range .OpenPorts }}
        {{ .Protocol }} . {{ .Port }},{{ if .Comment }} # {{ .Comment }}{{ end }}
{{- end }}
{{- end }}
    }
}
`

const whitelistTemplate = `# Generated by cnftctl. Manual edits may be overwritten.
# Static administrative source addresses allowed to SSH in hardened modes.

define whitelist_v4 = {{ nftSet .WhitelistIPv4 }}
define whitelist_v6 = {{ nftSet .WhitelistIPv6 }}
`

const ddnsHostsTemplate = `# Generated by cnftctl. Manual edits may be overwritten.
# Hostnames whose current A/AAAA records should be allowed to SSH.
{{- if .DDNSHosts }}
{{ range .DDNSHosts }}{{ . }}
{{ end -}}
{{- end }}
`

const ddnsServiceTemplate = `[Unit]
Description=Update nftables DDNS SSH whitelist
Wants=network-online.target nftables.service
After=network-online.target nftables.service

[Service]
Type=oneshot
ExecStart=/usr/bin/cnftctl ddns refresh
`

const ddnsTimerTemplate = `[Unit]
Description=Refresh nftables DDNS SSH whitelist periodically

[Timer]
OnBootSec=1min
OnUnitActiveSec={{ .DDNSRefresh }}
AccuracySec=30s
Persistent=true

[Install]
WantedBy=timers.target
`
